version: '3.9'

services:
  backend:
    build: ./data
    ports:
      - "5000:5000"
    volumes:
      - ./data/data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
