services:
  - type: web
    name: frontend
    env: docker
    plan: starter  # atau "professional" kalau kamu pakai yang premium
    repo: https://github.com/sekaralishaa/arxiv
    dockerfilePath: frontend/Dockerfile
    buildCommand: ""
    startCommand: "streamlit run app.py --server.port=10000 --server.address=0.0.0.0"
    envVars:
      - key: BACKEND_URL
        value: http://backend:5000

  - type: web
    name: backend
    env: docker
    plan: starter  # atau "professional"
    repo: https://github.com/sekaralishaa/arxiv
    dockerfilePath: data/Dockerfile
    buildCommand: ""
    startCommand: "python main.py"
    envVars: []
