services:
  - type: web
    name: frontend
    env: docker
    plan: professional  # kamu pilih plan premium
    dockerfilePath: frontend/Dockerfile
    buildCommand: ""
    startCommand: streamlit run app.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: BACKEND_URL
        value: http://backend:5000

  - type: web
    name: backend
    env: docker
    plan: professional
    dockerfilePath: data/Dockerfile
    buildCommand: ""
    startCommand: python main.py
    envVars: []

